# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './list_gui/duplicate_toolbar.ui'
#
# Created: Wed May 31 16:48:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/duplicate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setMaximumSize(QtCore.QSize(1200, 120))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_list_add_folder = QtGui.QPushButton(self.centralwidget)
        self.btn_list_add_folder.setObjectName("btn_list_add_folder")
        self.horizontalLayout_4.addWidget(self.btn_list_add_folder)
        self.btn_list_del_folder = QtGui.QPushButton(self.centralwidget)
        self.btn_list_del_folder.setObjectName("btn_list_del_folder")
        self.horizontalLayout_4.addWidget(self.btn_list_del_folder)
        self.btn_list_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_list_clear.setObjectName("btn_list_clear")
        self.horizontalLayout_4.addWidget(self.btn_list_clear)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.progressBar.setProperty("value", 35)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(1200, 1000))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.le_nfile = QtGui.QLineEdit(self.centralwidget)
        self.le_nfile.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_nfile.setObjectName("le_nfile")
        self.horizontalLayout_5.addWidget(self.le_nfile)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.le_nfolder = QtGui.QLineEdit(self.centralwidget)
        self.le_nfolder.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_nfolder.setObjectName("le_nfolder")
        self.horizontalLayout_5.addWidget(self.le_nfolder)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.le_sizeName = QtGui.QLineEdit(self.centralwidget)
        self.le_sizeName.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_sizeName.setObjectName("le_sizeName")
        self.horizontalLayout_5.addWidget(self.le_sizeName)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.le_sameCrc = QtGui.QLineEdit(self.centralwidget)
        self.le_sameCrc.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_sameCrc.setObjectName("le_sameCrc")
        self.horizontalLayout_5.addWidget(self.le_sameCrc)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuScan = QtGui.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon1)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionRun = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon3)
        self.actionRun.setObjectName("actionRun")
        self.actionSame_Name = QtGui.QAction(MainWindow)
        self.actionSame_Name.setCheckable(True)
        self.actionSame_Name.setChecked(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/same_name.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSame_Name.setIcon(icon4)
        self.actionSame_Name.setObjectName("actionSame_Name")
        self.actionSame_CSC = QtGui.QAction(MainWindow)
        self.actionSame_CSC.setCheckable(True)
        self.actionSame_CSC.setChecked(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/checksum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSame_CSC.setIcon(icon5)
        self.actionSame_CSC.setObjectName("actionSame_CSC")
        self.actionSettings = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/crc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon6)
        self.actionSettings.setObjectName("actionSettings")
        self.actionMove = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove.setIcon(icon7)
        self.actionMove.setObjectName("actionMove")
        self.actionInfo = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon8)
        self.actionInfo.setShortcut("")
        self.actionInfo.setObjectName("actionInfo")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon9)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuScan.addAction(self.actionRun)
        self.menuScan.addSeparator()
        self.menuScan.addAction(self.actionSame_Name)
        self.menuScan.addAction(self.actionSame_CSC)
        self.menuScan.addSeparator()
        self.menuScan.addAction(self.actionSettings)
        self.menuScan.addSeparator()
        self.menuScan.addAction(self.actionMove)
        self.menuHelp.addAction(self.actionInfo)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSame_Name)
        self.toolBar.addAction(self.actionSame_CSC)
        self.toolBar.addAction(self.actionMove)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btn_list_add_folder, QtCore.SIGNAL("clicked()"), MainWindow.func_list_add_folder)
        QtCore.QObject.connect(self.btn_list_del_folder, QtCore.SIGNAL("clicked()"), MainWindow.func_list_remove_folder)
        QtCore.QObject.connect(self.btn_list_clear, QtCore.SIGNAL("clicked()"), MainWindow.func_list_clear)
        QtCore.QObject.connect(self.actionMove, QtCore.SIGNAL("triggered()"), MainWindow.func_move_files)
        QtCore.QObject.connect(self.actionRun, QtCore.SIGNAL("triggered()"), MainWindow.RunProgram)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), MainWindow.func_load_scan)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), MainWindow.func_save_scan)
        QtCore.QObject.connect(self.actionSettings, QtCore.SIGNAL("triggered()"), MainWindow.func_show_settings)
        QtCore.QObject.connect(self.actionSame_CSC, QtCore.SIGNAL("triggered()"), MainWindow.func_same_csc)
        QtCore.QObject.connect(self.actionInfo, QtCore.SIGNAL("triggered()"), MainWindow.func_show_info)
        QtCore.QObject.connect(self.actionSame_Name, QtCore.SIGNAL("triggered()"), MainWindow.func_same_name)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_list_add_folder.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_list_del_folder.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_list_clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "N File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "N Foler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Size Same Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Size Same CRC", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScan.setTitle(QtGui.QApplication.translate("MainWindow", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSame_Name.setText(QtGui.QApplication.translate("MainWindow", "Same Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSame_CSC.setText(QtGui.QApplication.translate("MainWindow", "Same CheckSum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSame_CSC.setToolTip(QtGui.QApplication.translate("MainWindow", "Same CheckSum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove.setText(QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove.setToolTip(QtGui.QApplication.translate("MainWindow", "Move Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

